{{- $root := . }}
{{- $namespace := include "nico-machine-a-tron.namespace" . }}
{{- $baseName := include "nico-machine-a-tron.name" . }}

{{- range $podName, $podConfig := .Values.pods }}
{{/*
Skip unconfigured pods
*/}}
{{- if not (and $podConfig (or (gt (len ($podConfig.machines | default dict)) 0) (gt (len ($podConfig.racks | default dict)) 0))) }}
{{- continue }}
{{- end }}

{{- $name := printf "%s-%s" $baseName $podName }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-bmc-mock
  namespace: {{ $namespace }}
  labels:
    {{- include "nico-machine-a-tron.labels" $root | nindent 4 }}
    app: {{ $baseName }}
    nvidia-infra-controller/mat-service: "true"
    nvidia-infra-controller/pod-name: {{ $podName | quote }}
spec:
  selector:
    {{- include "nico-machine-a-tron.selectorLabels" $root | nindent 4 }}
    nvidia-infra-controller/pod-name: {{ $podName | quote }}
  ports:
    - port: {{ $root.Values.service.bmcMock.port }}
      name: redfish
      targetPort: redfish
      protocol: TCP
    {{- if $root.Values.machineATron.mockBmcSshServer }}
    - port: {{ $root.Values.service.ssh.port }}
      name: ssh
      targetPort: ssh
      protocol: TCP
    {{- end }}
{{- end }}
