// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the MachineValidationStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MachineValidationStatus{}

// MachineValidationStatus Progress and outcome of a Machine validation run
type MachineValidationStatus struct {
	// Current state or completed outcome of the validation run.
	State string `json:"state"`
	// Total number of validation tests in the run.
	Total int32 `json:"total"`
	// Number of validation tests that have completed.
	Completed int32 `json:"completed"`
}

type _MachineValidationStatus MachineValidationStatus

// NewMachineValidationStatus instantiates a new MachineValidationStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMachineValidationStatus(state string, total int32, completed int32) *MachineValidationStatus {
	this := MachineValidationStatus{}
	this.State = state
	this.Total = total
	this.Completed = completed
	return &this
}

// NewMachineValidationStatusWithDefaults instantiates a new MachineValidationStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMachineValidationStatusWithDefaults() *MachineValidationStatus {
	this := MachineValidationStatus{}
	return &this
}

// GetState returns the State field value
func (o *MachineValidationStatus) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *MachineValidationStatus) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *MachineValidationStatus) SetState(v string) {
	o.State = v
}

// GetTotal returns the Total field value
func (o *MachineValidationStatus) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *MachineValidationStatus) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *MachineValidationStatus) SetTotal(v int32) {
	o.Total = v
}

// GetCompleted returns the Completed field value
func (o *MachineValidationStatus) GetCompleted() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Completed
}

// GetCompletedOk returns a tuple with the Completed field value
// and a boolean to check if the value has been set.
func (o *MachineValidationStatus) GetCompletedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Completed, true
}

// SetCompleted sets field value
func (o *MachineValidationStatus) SetCompleted(v int32) {
	o.Completed = v
}

func (o MachineValidationStatus) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MachineValidationStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["state"] = o.State
	toSerialize["total"] = o.Total
	toSerialize["completed"] = o.Completed
	return toSerialize, nil
}

func (o *MachineValidationStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"state",
		"total",
		"completed",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMachineValidationStatus := _MachineValidationStatus{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMachineValidationStatus)

	if err != nil {
		return err
	}

	*o = MachineValidationStatus(varMachineValidationStatus)

	return err
}

type NullableMachineValidationStatus struct {
	value *MachineValidationStatus
	isSet bool
}

func (v NullableMachineValidationStatus) Get() *MachineValidationStatus {
	return v.value
}

func (v *NullableMachineValidationStatus) Set(val *MachineValidationStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableMachineValidationStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableMachineValidationStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMachineValidationStatus(val *MachineValidationStatus) *NullableMachineValidationStatus {
	return &NullableMachineValidationStatus{value: val, isSet: true}
}

func (v NullableMachineValidationStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMachineValidationStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
