// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the MachineValidationRunCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MachineValidationRunCreateRequest{}

// MachineValidationRunCreateRequest Optional filters for an on-demand Machine validation run
type MachineValidationRunCreateRequest struct {
	// Tags used to select validation tests.
	Tags []string `json:"tags,omitempty"`
	// Validation test names allowed for this run.
	AllowedTests []string `json:"allowedTests,omitempty"`
	// Whether unverified validation tests may run.
	RunUnverifiedTests *bool `json:"runUnverifiedTests,omitempty"`
	// Contexts used to select validation tests.
	Contexts []string `json:"contexts,omitempty"`
}

// NewMachineValidationRunCreateRequest instantiates a new MachineValidationRunCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMachineValidationRunCreateRequest() *MachineValidationRunCreateRequest {
	this := MachineValidationRunCreateRequest{}
	var runUnverifiedTests bool = false
	this.RunUnverifiedTests = &runUnverifiedTests
	return &this
}

// NewMachineValidationRunCreateRequestWithDefaults instantiates a new MachineValidationRunCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMachineValidationRunCreateRequestWithDefaults() *MachineValidationRunCreateRequest {
	this := MachineValidationRunCreateRequest{}
	var runUnverifiedTests bool = false
	this.RunUnverifiedTests = &runUnverifiedTests
	return &this
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *MachineValidationRunCreateRequest) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineValidationRunCreateRequest) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *MachineValidationRunCreateRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *MachineValidationRunCreateRequest) SetTags(v []string) {
	o.Tags = v
}

// GetAllowedTests returns the AllowedTests field value if set, zero value otherwise.
func (o *MachineValidationRunCreateRequest) GetAllowedTests() []string {
	if o == nil || IsNil(o.AllowedTests) {
		var ret []string
		return ret
	}
	return o.AllowedTests
}

// GetAllowedTestsOk returns a tuple with the AllowedTests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineValidationRunCreateRequest) GetAllowedTestsOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedTests) {
		return nil, false
	}
	return o.AllowedTests, true
}

// HasAllowedTests returns a boolean if a field has been set.
func (o *MachineValidationRunCreateRequest) HasAllowedTests() bool {
	if o != nil && !IsNil(o.AllowedTests) {
		return true
	}

	return false
}

// SetAllowedTests gets a reference to the given []string and assigns it to the AllowedTests field.
func (o *MachineValidationRunCreateRequest) SetAllowedTests(v []string) {
	o.AllowedTests = v
}

// GetRunUnverifiedTests returns the RunUnverifiedTests field value if set, zero value otherwise.
func (o *MachineValidationRunCreateRequest) GetRunUnverifiedTests() bool {
	if o == nil || IsNil(o.RunUnverifiedTests) {
		var ret bool
		return ret
	}
	return *o.RunUnverifiedTests
}

// GetRunUnverifiedTestsOk returns a tuple with the RunUnverifiedTests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineValidationRunCreateRequest) GetRunUnverifiedTestsOk() (*bool, bool) {
	if o == nil || IsNil(o.RunUnverifiedTests) {
		return nil, false
	}
	return o.RunUnverifiedTests, true
}

// HasRunUnverifiedTests returns a boolean if a field has been set.
func (o *MachineValidationRunCreateRequest) HasRunUnverifiedTests() bool {
	if o != nil && !IsNil(o.RunUnverifiedTests) {
		return true
	}

	return false
}

// SetRunUnverifiedTests gets a reference to the given bool and assigns it to the RunUnverifiedTests field.
func (o *MachineValidationRunCreateRequest) SetRunUnverifiedTests(v bool) {
	o.RunUnverifiedTests = &v
}

// GetContexts returns the Contexts field value if set, zero value otherwise.
func (o *MachineValidationRunCreateRequest) GetContexts() []string {
	if o == nil || IsNil(o.Contexts) {
		var ret []string
		return ret
	}
	return o.Contexts
}

// GetContextsOk returns a tuple with the Contexts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineValidationRunCreateRequest) GetContextsOk() ([]string, bool) {
	if o == nil || IsNil(o.Contexts) {
		return nil, false
	}
	return o.Contexts, true
}

// HasContexts returns a boolean if a field has been set.
func (o *MachineValidationRunCreateRequest) HasContexts() bool {
	if o != nil && !IsNil(o.Contexts) {
		return true
	}

	return false
}

// SetContexts gets a reference to the given []string and assigns it to the Contexts field.
func (o *MachineValidationRunCreateRequest) SetContexts(v []string) {
	o.Contexts = v
}

func (o MachineValidationRunCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MachineValidationRunCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.AllowedTests) {
		toSerialize["allowedTests"] = o.AllowedTests
	}
	if !IsNil(o.RunUnverifiedTests) {
		toSerialize["runUnverifiedTests"] = o.RunUnverifiedTests
	}
	if !IsNil(o.Contexts) {
		toSerialize["contexts"] = o.Contexts
	}
	return toSerialize, nil
}

type NullableMachineValidationRunCreateRequest struct {
	value *MachineValidationRunCreateRequest
	isSet bool
}

func (v NullableMachineValidationRunCreateRequest) Get() *MachineValidationRunCreateRequest {
	return v.value
}

func (v *NullableMachineValidationRunCreateRequest) Set(val *MachineValidationRunCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMachineValidationRunCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMachineValidationRunCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMachineValidationRunCreateRequest(val *MachineValidationRunCreateRequest) *NullableMachineValidationRunCreateRequest {
	return &NullableMachineValidationRunCreateRequest{value: val, isSet: true}
}

func (v NullableMachineValidationRunCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMachineValidationRunCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
