// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the MachineValidationRun type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MachineValidationRun{}

// MachineValidationRun Machine validation run
type MachineValidationRun struct {
	// ID of the Machine validation run.
	ValidationID string `json:"validationID"`
	// ID of the validated Machine.
	MachineID string `json:"machineID"`
	// Time the validation run started.
	StartTime time.Time `json:"startTime"`
	// Time the validation run completed, or null while it is active.
	EndTime NullableTime `json:"endTime"`
	// Name of the validation run.
	Name string `json:"name"`
	// Context in which the validation run was created.
	Context string                  `json:"context"`
	Status  MachineValidationStatus `json:"status"`
	// Estimated maximum duration of the validation run in seconds. A value of zero can mean the estimate has not yet been calculated.
	DurationToCompleteSecs int32 `json:"durationToCompleteSecs"`
}

type _MachineValidationRun MachineValidationRun

// NewMachineValidationRun instantiates a new MachineValidationRun object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMachineValidationRun(validationID string, machineID string, startTime time.Time, endTime NullableTime, name string, context string, status MachineValidationStatus, durationToCompleteSecs int32) *MachineValidationRun {
	this := MachineValidationRun{}
	this.ValidationID = validationID
	this.MachineID = machineID
	this.StartTime = startTime
	this.EndTime = endTime
	this.Name = name
	this.Context = context
	this.Status = status
	this.DurationToCompleteSecs = durationToCompleteSecs
	return &this
}

// NewMachineValidationRunWithDefaults instantiates a new MachineValidationRun object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMachineValidationRunWithDefaults() *MachineValidationRun {
	this := MachineValidationRun{}
	return &this
}

// GetValidationID returns the ValidationID field value
func (o *MachineValidationRun) GetValidationID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ValidationID
}

// GetValidationIDOk returns a tuple with the ValidationID field value
// and a boolean to check if the value has been set.
func (o *MachineValidationRun) GetValidationIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValidationID, true
}

// SetValidationID sets field value
func (o *MachineValidationRun) SetValidationID(v string) {
	o.ValidationID = v
}

// GetMachineID returns the MachineID field value
func (o *MachineValidationRun) GetMachineID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MachineID
}

// GetMachineIDOk returns a tuple with the MachineID field value
// and a boolean to check if the value has been set.
func (o *MachineValidationRun) GetMachineIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MachineID, true
}

// SetMachineID sets field value
func (o *MachineValidationRun) SetMachineID(v string) {
	o.MachineID = v
}

// GetStartTime returns the StartTime field value
func (o *MachineValidationRun) GetStartTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value
// and a boolean to check if the value has been set.
func (o *MachineValidationRun) GetStartTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartTime, true
}

// SetStartTime sets field value
func (o *MachineValidationRun) SetStartTime(v time.Time) {
	o.StartTime = v
}

// GetEndTime returns the EndTime field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *MachineValidationRun) GetEndTime() time.Time {
	if o == nil || o.EndTime.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.EndTime.Get()
}

// GetEndTimeOk returns a tuple with the EndTime field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MachineValidationRun) GetEndTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndTime.Get(), o.EndTime.IsSet()
}

// SetEndTime sets field value
func (o *MachineValidationRun) SetEndTime(v time.Time) {
	o.EndTime.Set(&v)
}

// GetName returns the Name field value
func (o *MachineValidationRun) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *MachineValidationRun) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *MachineValidationRun) SetName(v string) {
	o.Name = v
}

// GetContext returns the Context field value
func (o *MachineValidationRun) GetContext() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Context
}

// GetContextOk returns a tuple with the Context field value
// and a boolean to check if the value has been set.
func (o *MachineValidationRun) GetContextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Context, true
}

// SetContext sets field value
func (o *MachineValidationRun) SetContext(v string) {
	o.Context = v
}

// GetStatus returns the Status field value
func (o *MachineValidationRun) GetStatus() MachineValidationStatus {
	if o == nil {
		var ret MachineValidationStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *MachineValidationRun) GetStatusOk() (*MachineValidationStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *MachineValidationRun) SetStatus(v MachineValidationStatus) {
	o.Status = v
}

// GetDurationToCompleteSecs returns the DurationToCompleteSecs field value
func (o *MachineValidationRun) GetDurationToCompleteSecs() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DurationToCompleteSecs
}

// GetDurationToCompleteSecsOk returns a tuple with the DurationToCompleteSecs field value
// and a boolean to check if the value has been set.
func (o *MachineValidationRun) GetDurationToCompleteSecsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DurationToCompleteSecs, true
}

// SetDurationToCompleteSecs sets field value
func (o *MachineValidationRun) SetDurationToCompleteSecs(v int32) {
	o.DurationToCompleteSecs = v
}

func (o MachineValidationRun) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MachineValidationRun) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["validationID"] = o.ValidationID
	toSerialize["machineID"] = o.MachineID
	toSerialize["startTime"] = o.StartTime
	toSerialize["endTime"] = o.EndTime.Get()
	toSerialize["name"] = o.Name
	toSerialize["context"] = o.Context
	toSerialize["status"] = o.Status
	toSerialize["durationToCompleteSecs"] = o.DurationToCompleteSecs
	return toSerialize, nil
}

func (o *MachineValidationRun) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"validationID",
		"machineID",
		"startTime",
		"endTime",
		"name",
		"context",
		"status",
		"durationToCompleteSecs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMachineValidationRun := _MachineValidationRun{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMachineValidationRun)

	if err != nil {
		return err
	}

	*o = MachineValidationRun(varMachineValidationRun)

	return err
}

type NullableMachineValidationRun struct {
	value *MachineValidationRun
	isSet bool
}

func (v NullableMachineValidationRun) Get() *MachineValidationRun {
	return v.value
}

func (v *NullableMachineValidationRun) Set(val *MachineValidationRun) {
	v.value = val
	v.isSet = true
}

func (v NullableMachineValidationRun) IsSet() bool {
	return v.isSet
}

func (v *NullableMachineValidationRun) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMachineValidationRun(val *MachineValidationRun) *NullableMachineValidationRun {
	return &NullableMachineValidationRun{value: val, isSet: true}
}

func (v NullableMachineValidationRun) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMachineValidationRun) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
